name: 'spellcheck'
on:
  pull_request:
  push:

jobs:
  spellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: matheus23/md-spellcheck-action@v4
        with:
          files-to-check: "*.md"
